"""create_governance_tables

Revision ID: 0897db7a143a
Revises: 9988705e5172
Create Date: 2026-08-16 10:03:31.784400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0897db7a143a'
down_revision: Union[str, None] = '9988705e5172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('approver_id', sa.UUID(), nullable=True),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_records_agent_run_id'), 'approval_records', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_approval_records_repository_id'), 'approval_records', ['repository_id'], unique=False)
    op.create_index(op.f('ix_approval_records_user_id'), 'approval_records', ['user_id'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('policy_name', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_decisions_agent_run_id'), 'policy_decisions', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_policy_decisions_repository_id'), 'policy_decisions', ['repository_id'], unique=False)
    op.create_index(op.f('ix_policy_decisions_user_id'), 'policy_decisions', ['user_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('impact_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_agent_run_id'), 'risk_assessments', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_repository_id'), 'risk_assessments', ['repository_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_user_id'), 'risk_assessments', ['user_id'], unique=False)
    op.create_table('workflow_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('decision_type', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('escalation_result', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_decisions_agent_run_id'), 'workflow_decisions', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_workflow_decisions_repository_id'), 'workflow_decisions', ['repository_id'], unique=False)
    op.create_index(op.f('ix_workflow_decisions_user_id'), 'workflow_decisions', ['user_id'], unique=False)
    op.create_index(op.f('ix_git_operations_operation_type'), 'git_operations', ['operation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_git_operations_operation_type'), table_name='git_operations')
    op.drop_index(op.f('ix_workflow_decisions_user_id'), table_name='workflow_decisions')
    op.drop_index(op.f('ix_workflow_decisions_repository_id'), table_name='workflow_decisions')
    op.drop_index(op.f('ix_workflow_decisions_agent_run_id'), table_name='workflow_decisions')
    op.drop_table('workflow_decisions')
    op.drop_index(op.f('ix_risk_assessments_user_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_repository_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_agent_run_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_policy_decisions_user_id'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_repository_id'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_agent_run_id'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index(op.f('ix_approval_records_user_id'), table_name='approval_records')
    op.drop_index(op.f('ix_approval_records_repository_id'), table_name='approval_records')
    op.drop_index(op.f('ix_approval_records_agent_run_id'), table_name='approval_records')
    op.drop_table('approval_records')
    # ### end Alembic commands ###
