"""create_agent_runs_and_steps_tables

Revision ID: 90354bbb7d2b
Revises: 2240dd64a7ba
Create Date: 2026-08-16 08:52:13.772437

"""
from typing import Sequence, Union

import app.core.database
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90354bbb7d2b'
down_revision: Union[str, None] = '2240dd64a7ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('parent_job_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_agent', sa.String(length=50), nullable=True),
    sa.Column('workflow_stage', sa.String(length=100), nullable=False),
    sa.Column('overall_progress', sa.Integer(), nullable=False),
    sa.Column('final_decision', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_job_id'], ['agent_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_created_at', 'agent_runs', ['created_at'], unique=False)
    op.create_index('ix_agent_runs_repository_id', 'agent_runs', ['repository_id'], unique=False)
    op.create_index('ix_agent_runs_status', 'agent_runs', ['status'], unique=False)
    op.create_index('ix_agent_runs_status_created_at', 'agent_runs', ['status', 'created_at'], unique=False)
    op.create_index('ix_agent_runs_task_id', 'agent_runs', ['task_id'], unique=False)
    op.create_index('ix_agent_runs_user_id', 'agent_runs', ['user_id'], unique=False)
    op.create_table('agent_run_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('output', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('started_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['agent_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_run_steps_agent_type', 'agent_run_steps', ['agent_type'], unique=False)
    op.create_index('ix_agent_run_steps_created_at', 'agent_run_steps', ['created_at'], unique=False)
    op.create_index('ix_agent_run_steps_run_id', 'agent_run_steps', ['run_id'], unique=False)
    op.create_index('ix_agent_run_steps_status', 'agent_run_steps', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_run_steps_status', table_name='agent_run_steps')
    op.drop_index('ix_agent_run_steps_run_id', table_name='agent_run_steps')
    op.drop_index('ix_agent_run_steps_created_at', table_name='agent_run_steps')
    op.drop_index('ix_agent_run_steps_agent_type', table_name='agent_run_steps')
    op.drop_table('agent_run_steps')
    op.drop_index('ix_agent_runs_user_id', table_name='agent_runs')
    op.drop_index('ix_agent_runs_task_id', table_name='agent_runs')
    op.drop_index('ix_agent_runs_status_created_at', table_name='agent_runs')
    op.drop_index('ix_agent_runs_status', table_name='agent_runs')
    op.drop_index('ix_agent_runs_repository_id', table_name='agent_runs')
    op.drop_index('ix_agent_runs_created_at', table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
