"""create_audit_events_table

Revision ID: 9988705e5172
Revises: 90354bbb7d2b
Create Date: 2026-08-16 09:52:02.065209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.core.database

# revision identifiers, used by Alembic.
revision: str = '9988705e5172'
down_revision: Union[str, None] = '90354bbb7d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('repository_id', sa.UUID(), nullable=True),
    sa.Column('agent_task_id', sa.UUID(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['agent_task_id'], ['agent_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['agent_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_events_repo_created', 'audit_events', ['repository_id', 'created_at'], unique=False)
    op.create_index('idx_audit_events_type_sev', 'audit_events', ['event_type', 'severity'], unique=False)
    op.create_index('idx_audit_events_user_created', 'audit_events', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_agent_run_id'), 'audit_events', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_audit_events_agent_task_id'), 'audit_events', ['agent_task_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_job_id'), 'audit_events', ['job_id'], unique=False)
    op.create_index(op.f('ix_audit_events_repository_id'), 'audit_events', ['repository_id'], unique=False)
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_events_severity'), 'audit_events', ['severity'], unique=False)
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_git_operations_operation_type'), table_name='git_operations')
    op.alter_column('code_chunks', 'embedding',
               existing_type=app.models.knowledge.HybridVector(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_severity'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_repository_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_job_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_agent_task_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_agent_run_id'), table_name='audit_events')
    op.drop_index('idx_audit_events_user_created', table_name='audit_events')
    op.drop_index('idx_audit_events_type_sev', table_name='audit_events')
    op.drop_index('idx_audit_events_repo_created', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
