"""step19_analytics

Revision ID: bc051daf4c17
Revises: 488671708f8e
Create Date: 2026-08-16 23:05:04.998295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc051daf4c17'
down_revision: Union[str, None] = '488671708f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_performance_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.String(length=100), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('successful_runs', sa.Integer(), nullable=False),
    sa.Column('failed_runs', sa.Integer(), nullable=False),
    sa.Column('average_duration_ms', sa.Float(), nullable=False),
    sa.Column('average_confidence', sa.Float(), nullable=False),
    sa.Column('repair_iterations', sa.Integer(), nullable=False),
    sa.Column('human_escalations', sa.Integer(), nullable=False),
    sa.Column('approval_rate', sa.Float(), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'agent_type', name='uq_org_agent_metric')
    )
    op.create_index(op.f('ix_agent_performance_metrics_agent_type'), 'agent_performance_metrics', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_performance_metrics_organization_id'), 'agent_performance_metrics', ['organization_id'], unique=False)
    op.create_table('analytics_retention_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_cleanup_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('usage_daily_aggregates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('api_requests', sa.Integer(), nullable=False),
    sa.Column('agent_runs', sa.Integer(), nullable=False),
    sa.Column('successful_runs', sa.Integer(), nullable=False),
    sa.Column('failed_runs', sa.Integer(), nullable=False),
    sa.Column('executions', sa.Integer(), nullable=False),
    sa.Column('successful_executions', sa.Integer(), nullable=False),
    sa.Column('failed_executions', sa.Integer(), nullable=False),
    sa.Column('repair_attempts', sa.Integer(), nullable=False),
    sa.Column('human_escalations', sa.Integer(), nullable=False),
    sa.Column('pr_creations', sa.Integer(), nullable=False),
    sa.Column('webhook_deliveries', sa.Integer(), nullable=False),
    sa.Column('webhook_failures', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_ai_cost', sa.Float(), nullable=False),
    sa.Column('compute_duration_ms', sa.Float(), nullable=False),
    sa.Column('job_retries', sa.Integer(), nullable=False),
    sa.Column('job_cancellations', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'date', name='uq_org_daily_aggregate')
    )
    op.create_index(op.f('ix_usage_daily_aggregates_date'), 'usage_daily_aggregates', ['date'], unique=False)
    op.create_index(op.f('ix_usage_daily_aggregates_organization_id'), 'usage_daily_aggregates', ['organization_id'], unique=False)
    op.create_table('usage_quotas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('quota_type', sa.String(length=100), nullable=False),
    sa.Column('limit_value', sa.Float(), nullable=False),
    sa.Column('current_usage', sa.Float(), nullable=False),
    sa.Column('warning_threshold', sa.Float(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('reset_period', sa.String(length=50), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'quota_type', name='uq_org_quota_type')
    )
    op.create_index(op.f('ix_usage_quotas_organization_id'), 'usage_quotas', ['organization_id'], unique=False)
    op.create_index(op.f('ix_usage_quotas_quota_type'), 'usage_quotas', ['quota_type'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('repository_id', sa.UUID(), nullable=True),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_agent_run_id'), 'usage_records', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_usage_records_created_at'), 'usage_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_records_event_type'), 'usage_records', ['event_type'], unique=False)
    op.create_index(op.f('ix_usage_records_idempotency_key'), 'usage_records', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_usage_records_job_id'), 'usage_records', ['job_id'], unique=False)
    op.create_index(op.f('ix_usage_records_model'), 'usage_records', ['model'], unique=False)
    op.create_index(op.f('ix_usage_records_organization_id'), 'usage_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_usage_records_provider'), 'usage_records', ['provider'], unique=False)
    op.create_index(op.f('ix_usage_records_repository_id'), 'usage_records', ['repository_id'], unique=False)
    op.create_index(op.f('ix_usage_records_user_id'), 'usage_records', ['user_id'], unique=False)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    op.drop_index(op.f('ix_usage_records_user_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_repository_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_provider'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_organization_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_model'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_job_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_idempotency_key'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_event_type'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_created_at'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_agent_run_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_usage_quotas_quota_type'), table_name='usage_quotas')
    op.drop_index(op.f('ix_usage_quotas_organization_id'), table_name='usage_quotas')
    op.drop_table('usage_quotas')
    op.drop_index(op.f('ix_usage_daily_aggregates_organization_id'), table_name='usage_daily_aggregates')
    op.drop_index(op.f('ix_usage_daily_aggregates_date'), table_name='usage_daily_aggregates')
    op.drop_table('usage_daily_aggregates')
    op.drop_table('analytics_retention_policies')
    op.drop_index(op.f('ix_agent_performance_metrics_organization_id'), table_name='agent_performance_metrics')
    op.drop_index(op.f('ix_agent_performance_metrics_agent_type'), table_name='agent_performance_metrics')
    op.drop_table('agent_performance_metrics')
    # ### end Alembic commands ###
