# Generated by Django 6.0.1 on 2026-01-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
